language: ruby
sudo: false
notifications:
  email:
    on_success: change
    on_failure: always

rvm: 
  - 1.8.7
  - 1.9.3
  - 2.2.2
  - 2.3.1
  - ruby-head

before_install:
  - gem --version
  - gem install bundler
  - bundle --version

matrix:
  allow_failures:
    - rvm: ruby-head

